name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${GITHUB_WORKSPACE}

    - name: Configure CMake
      working-directory: ${{runner.workspace}}    
      run: cmake -H${GITHUB_WORKSPACE} -B ${GITHUB_WORKSPACE}/build  -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE=on "-GUnix Makefiles"

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build ${GITHUB_WORKSPACE}/build --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}
      shell: bash
      run: ctest --test-dir ${GITHUB_WORKSPACE}/build -C $BUILD_TYPE
